import { defineConfig } from "vite";
import { readdir, unlink, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const sourceAliases = {
  "omnicam-webgl": "viewport.js",
  "omnicam-history": "director/history.js",
  "omnicam-playblast": "director/playblast.js", "omnicam-media": "director/media.js",
  "omnicam-template": "template.js",
  "omnicam-commands": "commands.js", "omnicam-state-sync": "state-sync.js",
  "omnicam-cameras": "cameras.js", "omnicam-record": "record.js",
  "omnicam-scene": "scene.js", "omnicam-timeline": "timeline.js",
  "omnicam-timeline-interaction": "timeline-interaction.js", "omnicam-curve-editor": "curve-editor.js",
  "omnicam-playback-transport": "playback-transport.js", "omnicam-motion-presets": "motion-presets.js",
  "omnicam-background-manager": "background-manager.js", "omnicam-viewport-overlays": "viewport-overlays.js",
  "omnicam-viewport-controls": "viewport-controls.js", "omnicam-event-bindings": "event-bindings.js",
  "omnicam-dom-media": "dom-media.js", "omnicam-diagnostics": "diagnostics.js",
};

// ComfyUI globs `**/*.js` under WEB_DIRECTORY and imports every hit as an
// extension, so a chunk emitted into web/ would be fetched eagerly at startup
// and code splitting would buy nothing. The bundle therefore builds into
// web-chunks/, served by omnicam/routes_chunks.py, and web/ holds only a stub
// that imports it. Keep this comment, the route module, and the stub in sync.
const STUB = `// Generated by vite.config.mjs -- do not edit.
//
// The only file ComfyUI loads as an extension. The real bundle and its lazy
// chunks live outside WEB_DIRECTORY so ComfyUI's extension glob cannot force
// them all to load; omnicam/routes_chunks.py serves them at the sibling URL
// below. The hop is relative so renaming the custom-node folder stays safe.
import "../majoor-omnicam-chunks/omnicam.js";
`;

function publicEntryStub() {
  return {
    name: "omnicam-public-entry-stub",
    resolveId(id) {
      const match = id.match(/(?:^|\/)omnicam-[^/]+\.js$/);
      const key = match?.[0].split("/").at(-1).replace(/\.js$/, "");
      return key && sourceAliases[key] ? resolve("web-src", sourceAliases[key]) : null;
    },
    async closeBundle() {
      // web/ must keep exactly one .js -- the stub -- or ComfyUI would load a
      // stale bundle from a previous single-file build alongside the new one.
      for (const file of await readdir("web")) {
        if (file.endsWith(".js")) await unlink(resolve("web", file));
      }
      await writeFile(resolve("web", "omnicam.js"), STUB, "utf8");
    },
  };
}

export default defineConfig(({ mode }) => ({
  plugins: [publicEntryStub()],
  build: {
    emptyOutDir: true,
    lib: {
      entry: { omnicam: "web-src/main.js" },
      formats: ["es"],
      fileName: (_format, entryName) => `${entryName}.js`,
    },
    rollupOptions: {
      // ComfyUI's own modules are resolved by the browser at the URL depth the
      // chunk route mirrors, so the relative specifier is left untouched.
      external: (id) => id.startsWith("../../scripts/"),
      output: {
        // Hashed names: the chunk route serves them as ordinary static files,
        // so a new build must not reuse a URL the browser already cached.
        chunkFileNames: "chunk-[hash].js",
        assetFileNames: "asset-[hash][extname]",
        manualChunks(id) {
          if (id.includes("node_modules/three")) return "vendor-three";
          if (id.includes("node_modules/mediabunny")) return "vendor-mediabunny";
          return null;
        },
      },
    },
    outDir: "web-chunks",
    // Development builds ship source maps for debugging; release artifacts stay compact.
    sourcemap: mode === "development" ? true : false,
    minify: mode === "development" ? false : "esbuild",
  },
}));
