import { t } from "./omnicam-i18n.js";

export const DIRECTOR_STYLES = `
      .majoor-omnicam{font:12px/1.35 system-ui,sans-serif;color:var(--fg-color,#ddd);background:#171717;border:1px solid #383838;border-radius:10px;overflow:hidden;user-select:none}
      .majoor-omnicam *{box-sizing:border-box}
      .majoor-omnicam .top{position:relative;z-index:10;display:flex;gap:4px;align-items:center;min-height:38px;padding:4px 6px;background:#202020;border-bottom:1px solid #333}
      .majoor-omnicam button,.majoor-omnicam select,.majoor-omnicam input{font:inherit;color:#eee;background:#2a2a2a;border:1px solid #444;border-radius:6px;padding:4px 7px}
      .majoor-omnicam button:hover{background:#343434}.majoor-omnicam button.primary{background:#3d5f48;border-color:#5f8f6b}.majoor-omnicam button.active{background:#713737;border-color:#ef6767;color:#fff}
      .majoor-omnicam .icon-button{display:inline-grid;place-items:center;width:28px;height:28px;min-width:28px;padding:0}.majoor-omnicam .icon-button .pi{font-size:13px}
      .majoor-omnicam .toolbar-menu{position:relative}.majoor-omnicam .toolbar-menu>summary{display:flex;align-items:center;gap:5px;min-height:28px;padding:4px 8px;border:1px solid transparent;border-radius:6px;cursor:pointer;white-space:nowrap;list-style:none}.majoor-omnicam .toolbar-menu>summary::-webkit-details-marker{display:none}.majoor-omnicam .toolbar-menu[open]>summary,.majoor-omnicam .toolbar-menu>summary:hover{background:#303030;border-color:#484848}
      .majoor-omnicam .menu-panel{position:absolute;z-index:50;top:calc(100% + 5px);left:0;display:flex;flex-direction:column;gap:4px;width:240px;padding:7px;background:#202020;border:1px solid #4a4a4a;border-radius:8px;box-shadow:0 10px 24px #000a}.majoor-omnicam .menu-panel.right{right:0;left:auto}.majoor-omnicam .menu-panel button{display:flex;align-items:center;gap:7px;text-align:left}.majoor-omnicam .menu-panel label{display:flex;align-items:center;justify-content:space-between;gap:8px;color:#bbb}.majoor-omnicam .menu-panel label>select,.majoor-omnicam .menu-panel label>input[type=number]{width:126px}.majoor-omnicam .menu-panel label>input[type=checkbox]{width:auto}.majoor-omnicam .menu-title{color:#888;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.majoor-omnicam .menu-divider{height:1px;margin:3px 0;background:#3a3a3a}.majoor-omnicam .camera-menu-list{display:flex;max-height:180px;flex-direction:column;gap:3px;overflow:auto}.majoor-omnicam .camera-menu-list button.selected{border-color:#e3c35d;color:#f2d06b}
      .majoor-omnicam .viewport-wrap{position:relative;width:100%;min-height:280px;aspect-ratio:16/9;background:#111;touch-action:none;overscroll-behavior:contain;pointer-events:auto;outline:none;box-shadow:inset 0 0 0 2px transparent;transition:box-shadow .12s ease}
      .majoor-omnicam .viewport-wrap.edit-mode{box-shadow:inset 0 0 0 3px #ef5350}.majoor-omnicam .viewport-wrap.auto-key{box-shadow:inset 0 0 0 3px #f0a52b}.majoor-omnicam .viewport-wrap.auto-key.edit-mode{box-shadow:inset 0 0 0 3px #ef5350,inset 0 0 0 6px #f0a52b}
      .majoor-omnicam canvas{display:block;width:100%;height:100%;pointer-events:auto;outline:none;cursor:grab}.majoor-omnicam canvas.dragging{cursor:grabbing}
      .majoor-omnicam .viewport-actions{position:absolute;z-index:5;left:9px;top:8px;display:flex;gap:5px}.majoor-omnicam .viewport-actions button{display:flex;align-items:center;gap:6px;background:#161616d9;backdrop-filter:blur(4px)}
      .majoor-omnicam .view-nav{position:absolute;z-index:6;left:9px;top:43px;display:flex;align-items:center;gap:5px;padding:4px 6px;border:1px solid #444;border-radius:5px;background:#161616e8}.majoor-omnicam .view-nav select{height:25px;min-width:108px}.majoor-omnicam .view-nav button{width:25px;height:25px;padding:0}
      .majoor-omnicam .viewport-state{position:absolute;z-index:4;right:10px;top:9px;display:none;padding:3px 7px;border-radius:4px;background:#000b;font-weight:700;letter-spacing:.04em;pointer-events:none}.majoor-omnicam .viewport-wrap.edit-mode .viewport-state,.majoor-omnicam .viewport-wrap.auto-key .viewport-state{display:block}.majoor-omnicam .viewport-wrap.edit-mode .viewport-state{color:#ff8c89}.majoor-omnicam .viewport-wrap.auto-key .viewport-state{color:#ffc45e}
      .majoor-omnicam .hud{position:absolute;left:10px;top:82px;color:#ddd;background:#0009;border-radius:5px;padding:5px 7px;pointer-events:none;white-space:pre}
      .majoor-omnicam .viewport-inspector{position:absolute;z-index:6;right:9px;top:42px;width:208px;max-height:calc(100% - 52px);overflow:auto;padding:7px;background:#181818e8;border:1px solid #4a4a4a;border-radius:7px;backdrop-filter:blur(5px)}
      .majoor-omnicam .camera-view-row{position:relative;display:flex;width:100%;padding:5px 30px 5px 5px;background:#181818;border-top:1px solid #333}.majoor-omnicam .camera-view-row[hidden]{display:none}.majoor-omnicam .camera-preview-strip{display:grid;width:100%;grid-auto-flow:column;grid-auto-columns:minmax(220px,calc((100% - 10px)/3));gap:5px;overflow-x:auto}.majoor-omnicam .camera-preview-tile{position:relative;min-width:0;height:clamp(150px,18vw,230px);overflow:hidden;background:#101010;border:1px solid #4c4c4c;border-top:4px solid var(--camera-color);border-radius:4px;cursor:pointer}.majoor-omnicam .camera-preview-tile.playblast{border-color:#f2d06b;border-top-color:#f2d06b;box-shadow:inset 0 0 0 1px #f2d06b}.majoor-omnicam .camera-preview-head{position:absolute;z-index:2;left:0;right:0;top:0;display:flex;align-items:center;gap:5px;min-height:25px;padding:3px 6px;background:#171717e8;color:#ddd;font-size:10px;font-weight:700;letter-spacing:.04em;pointer-events:none}.majoor-omnicam .camera-preview-head .output-mark{margin-left:auto;color:#f2d06b}.majoor-omnicam .camera-preview-tile canvas{width:100%;height:100%;cursor:pointer}.majoor-omnicam .camera-view-badge{position:absolute;left:6px;bottom:5px;padding:2px 5px;border-radius:3px;background:#000b;color:#ddd;font-size:9px;pointer-events:none}.majoor-omnicam .camera-strip-close{position:absolute;right:4px;top:5px;width:23px;height:23px;padding:0}
      .majoor-omnicam .camera-preview-strip[data-layout="1"]{grid-auto-columns:100%}.majoor-omnicam .camera-preview-strip[data-layout="2"]{grid-auto-columns:calc((100% - 5px)/2)}.majoor-omnicam .camera-preview-strip[data-layout="4"]{grid-auto-flow:row;grid-template-columns:1fr 1fr;grid-auto-rows:minmax(140px,1fr)}
      .majoor-omnicam .camera-preview-strip[data-layout="4"] .camera-preview-tile{height:auto;min-height:140px}
      .majoor-omnicam .camera-view-row.maximized .camera-preview-strip{display:block;position:relative}.majoor-omnicam .camera-view-row.maximized .camera-preview-tile{display:none}.majoor-omnicam .camera-view-row.maximized .camera-preview-tile.maximized{display:block;height:min(60vh,480px)}
      .majoor-omnicam .scene-tree{display:flex;flex-direction:column;gap:2px;margin-bottom:6px}.majoor-omnicam .scene-item{display:flex;align-items:center;gap:6px;width:100%;min-height:24px;padding:3px 6px;text-align:left;border-color:transparent;background:transparent}.majoor-omnicam .scene-item.selected{background:#35506c;border-color:#6f9bca}.majoor-omnicam .scene-item .pi{width:14px;text-align:center}
      .majoor-omnicam .transform-tools{display:flex;gap:3px;margin:5px 0}.majoor-omnicam .transform-tools button{width:28px;height:25px;padding:0}.majoor-omnicam .transform-tools button.active{background:#3f6282;border-color:#72a4d4}.majoor-omnicam .transform-tools select{min-width:0;flex:1;padding:2px 4px}
      .majoor-omnicam .viewport-grid{display:grid;grid-template-columns:1fr 66px;gap:3px 5px}.majoor-omnicam .viewport-grid label{display:contents}.majoor-omnicam .viewport-grid span{align-self:center;color:#bbb}.majoor-omnicam .viewport-grid input{width:66px;padding:2px 4px}.majoor-omnicam .entity-panel[hidden]{display:none}.majoor-omnicam .animation-row{display:flex;gap:5px;align-items:center;margin-top:6px}.majoor-omnicam .animation-row select{min-width:0;flex:1}
      .majoor-omnicam.recording [data-act="record"]{background:#7c3030;border-color:#d85b5b}
      .majoor-omnicam .timeline{padding:8px;background:#1b1b1b;border-top:1px solid #333}
      .majoor-omnicam .row{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.majoor-omnicam .row + .row{margin-top:6px}
      .majoor-omnicam input[type=range]{padding:0;flex:1;min-width:160px}.majoor-omnicam input[type=number]{width:68px}
      .majoor-omnicam .timeline-toolbar{justify-content:flex-start;gap:4px}.majoor-omnicam .timeline-summary{margin-left:auto;color:#aaa}.majoor-omnicam .toolbar-divider{width:1px;height:20px;margin:0 3px;background:#3c3c3c}
      .majoor-omnicam .keys{position:relative;width:100%;height:68px;margin-top:7px;overflow:hidden;background:linear-gradient(#202020,#181818);border:1px solid #414141;border-radius:6px;cursor:crosshair;outline:none;touch-action:none}
      .majoor-omnicam .keys:focus-visible{border-color:#88a8e8;box-shadow:0 0 0 1px #88a8e8}
      .majoor-omnicam .timeline-tick{position:absolute;top:0;height:100%;border-left:1px solid #3c3c3c;color:#8d8d8d;font-size:10px;padding:2px 0 0 4px;pointer-events:none}
      .majoor-omnicam .timeline-marker{position:absolute;z-index:2;top:0;bottom:0;width:1px;background:var(--marker-color,#f2d06b);pointer-events:none}.majoor-omnicam .timeline-marker::before{content:"";position:absolute;left:-4px;top:0;border-left:4px solid transparent;border-right:4px solid transparent;border-top:6px solid var(--marker-color,#f2d06b)}
      .majoor-omnicam .playback-range{position:absolute;top:0;bottom:0;background:#f2d06b14;border-left:1px solid #f2d06b88;border-right:1px solid #f2d06b88;pointer-events:none}
      .majoor-omnicam .box-select{position:absolute;z-index:4;border:1px dashed #8ab4f8;background:#8ab4f822;pointer-events:none}
      .majoor-omnicam .playhead{position:absolute;z-index:2;top:0;bottom:0;width:1px;background:#f2d06b;pointer-events:none}.majoor-omnicam .playhead::before{content:"";position:absolute;left:-5px;top:0;border-left:5px solid transparent;border-right:5px solid transparent;border-top:8px solid #f2d06b}
      .majoor-omnicam .key{appearance:none;position:absolute;z-index:3;top:16px;width:34px;height:47px;transform:translateX(-50%);padding:0;border:0;background:transparent;cursor:ew-resize;color:#aaa;outline:none}
      .majoor-omnicam .key::before{content:"";position:absolute;left:11px;top:4px;width:12px;height:12px;transform:rotate(45deg);border:2px solid #9db2dc;background:#405273;border-radius:2px}
      .majoor-omnicam .key:hover::before,.majoor-omnicam .key:focus-visible::before{border-color:#fff}.majoor-omnicam .key.at-playhead::before{border-color:#f2d06b}.majoor-omnicam .key.selected::before{background:#f2d06b;border-color:#fff0ad;box-shadow:0 0 0 2px #f2d06b55}.majoor-omnicam .key.editing::before{background:#e34f4f;border-color:#ffc0c0;box-shadow:0 0 0 2px #e34f4f66}
      .majoor-omnicam .key-label{position:absolute;top:24px;left:0;width:34px;text-align:center;font-size:10px;font-weight:600}
      .majoor-omnicam .curve-editor{margin-top:6px;border:1px solid #393939;border-radius:6px;background:#151515}.majoor-omnicam .curve-editor>summary{display:flex;align-items:center;gap:6px;min-height:29px;padding:4px 7px;cursor:pointer;list-style:none}.majoor-omnicam .curve-editor>summary::-webkit-details-marker{display:none}.majoor-omnicam .curve-toolbar{display:flex;align-items:center;gap:4px;padding:0 6px 5px;flex-wrap:wrap}.majoor-omnicam .curve-toolbar select{height:27px;padding:2px 5px}.majoor-omnicam .curve-mode{height:27px;padding:2px 6px}.majoor-omnicam .curve-mode.active{background:#644536;border-color:#d18a57}.majoor-omnicam [data-tangent-mode].active{background:#2e4a64;border-color:#6f9bca}.majoor-omnicam .curve-canvas{display:block;width:100%;height:178px;border-top:1px solid #333;background:#111;cursor:crosshair;touch-action:none}
      .majoor-omnicam .context-menu{position:fixed;z-index:100000;display:flex;min-width:220px;max-width:290px;flex-direction:column;gap:2px;padding:6px;background:#202020;border:1px solid #555;border-radius:8px;box-shadow:0 12px 30px #000c}.majoor-omnicam .context-menu[hidden]{display:none}.majoor-omnicam .context-menu button{display:flex;align-items:center;gap:8px;width:100%;min-height:28px;text-align:left;border-color:transparent;background:transparent}.majoor-omnicam .context-menu button:hover,.majoor-omnicam .context-menu button:focus-visible{background:#373737;border-color:#555}.majoor-omnicam .context-menu button:disabled{opacity:.4}.majoor-omnicam .context-menu .danger{color:#ff9995}.majoor-omnicam .context-menu .shortcut{margin-left:auto;color:#888;font-size:10px}.majoor-omnicam .context-menu-separator{height:1px;margin:3px;background:#414141}.majoor-omnicam .context-menu-title{padding:3px 7px;color:#999;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
      .majoor-omnicam .compact-panel{margin-top:6px;border:1px solid #353535;border-radius:6px;background:#202020}.majoor-omnicam .compact-panel>summary{display:flex;align-items:center;gap:6px;min-height:28px;padding:4px 7px;cursor:pointer;color:#ccc;list-style:none}.majoor-omnicam .compact-panel>summary::-webkit-details-marker{display:none}.majoor-omnicam .compact-panel>summary::after{content:"›";margin-left:auto;transform:rotate(90deg);color:#777}.majoor-omnicam .compact-panel[open]>summary::after{transform:rotate(-90deg)}.majoor-omnicam .panel-body{padding:0 7px 7px}
      .majoor-omnicam .key-editor-header{display:flex;align-items:center;gap:5px;flex-wrap:wrap;margin-bottom:6px}.majoor-omnicam .key-editor-grid,.majoor-omnicam .inspector-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(112px,1fr));gap:5px}.majoor-omnicam .key-editor-grid label,.majoor-omnicam .inspector-grid label{display:flex;align-items:center;justify-content:space-between;gap:4px;color:#bbb}.majoor-omnicam .key-editor-grid input,.majoor-omnicam .key-editor-grid select,.majoor-omnicam .inspector-grid input,.majoor-omnicam .inspector-grid select{min-width:0;width:70px}.majoor-omnicam .key-editor[data-empty="true"] .key-editor-grid{opacity:.45}
      .majoor-omnicam .status{margin-left:auto;color:#aaa}.majoor-omnicam .hint{color:#aaa;font-size:11px}
      .majoor-omnicam .objects{display:flex;gap:5px;flex-wrap:wrap}.majoor-omnicam .badge{background:#282828;border:1px solid #3d3d3d;border-radius:10px;padding:2px 6px}
      .majoor-omnicam .badge.selected{border-color:#85a6e8;background:#34415a}
      .majoor-omnicam details.help{padding:7px 10px;background:#181818;color:#c8c8c8}.majoor-omnicam details.help summary{cursor:pointer;color:#f2d06b}.majoor-omnicam details.help p{margin:6px 0}
      .majoor-omnicam .setup-badge{display:flex;align-items:center;gap:6px;padding:4px 6px;border-radius:5px;font-size:10px;font-weight:700}.majoor-omnicam .setup-badge.ok{color:#7fd08a;background:#1e2c1f}.majoor-omnicam .setup-badge.warn{color:#ffc45e;background:#2d2415}.majoor-omnicam .setup-badge.error{color:#ff8c89;background:#2d1a1a}
      .majoor-omnicam .setup-issue{color:#bbb;font-size:11px;line-height:1.4}.majoor-omnicam .setup-issue a{color:#8ab4f8}
      .majoor-omnicam[data-density="basic"] .viewport-inspector,.majoor-omnicam[data-density="basic"] .curve-editor,.majoor-omnicam[data-density="basic"] .key-editor,.majoor-omnicam[data-density="basic"] [data-menu="camera"] .menu-panel label,.majoor-omnicam[data-density="basic"] [data-menu="show"] .menu-panel label:has([data-role="speed-heatmap"]){display:none}
      .majoor-omnicam[data-density="animation"] .viewport-inspector{display:none}
`;

export function buildRoot() {
  const root = document.createElement("div");
  root.className = "majoor-omnicam";
  root.dataset.density = "advanced";
  root.innerHTML = `
    <style>${DIRECTOR_STYLES}</style>
    <div class="top">
      <details class="toolbar-menu" data-menu="scene"><summary><i class="pi pi-box"></i> ${t("Scene")} <i class="pi pi-chevron-down"></i></summary><div class="menu-panel">
        <div class="menu-title">${t("Cards & models")}</div>
        <button data-act="load-card"><i class="pi pi-image"></i> ${t("Set Subject Card")}</button><button data-act="add-card"><i class="pi pi-images"></i> ${t("Add Media Card")}</button><button data-act="load-model"><i class="pi pi-box"></i> ${t("Import 3D Scene")}</button><span class="hint">${t("GLB, OBJ, FBX, STL, PLY. Convert ABC first.")}</span>
        <div class="menu-divider"></div><div class="menu-title">${t("Objects")}</div>
        <button data-object-type="ground"><i class="pi pi-minus"></i> ${t("Ground")}</button><button data-object-type="cube"><i class="pi pi-stop"></i> ${t("Cube")}</button><button data-object-type="sphere"><i class="pi pi-circle"></i> ${t("Sphere")}</button><button data-object-type="human"><i class="pi pi-user"></i> ${t("Human Proxy")}</button><button data-object-type="null"><i class="pi pi-plus"></i> ${t("Null")}</button>
      </div></details>
      <input data-role="file" type="file" accept="image/*,video/*" hidden><input data-role="model-file" type="file" accept=".glb,.obj,.fbx,.stl,.ply" hidden>
      <details class="toolbar-menu" data-menu="camera"><summary><i class="pi pi-video"></i> <span data-role="camera-summary">${t("Camera 1 · Key F0")}</span> <i class="pi pi-chevron-down"></i></summary><div class="menu-panel">
        <div class="menu-title">${t("Animated cameras")}</div><div class="camera-menu-list" data-role="camera-menu-list"></div><button data-act="add-camera"><i class="pi pi-plus"></i> ${t("Add Camera")}</button><div class="menu-divider"></div>
        <label>${t("FOV")} <input data-role="fov" type="number" min="5" max="150" step="1" value="35"></label><label>${t("Roll")} <input data-role="roll" type="number" min="-180" max="180" step="1" value="0"></label><label>${t("Move speed")} <input data-role="speed" type="number" min="0.05" max="5" step="0.05" value="1"></label>
        <label>${t("Projection")} <select data-role="camera-type"><option value="perspective">${t("Perspective")}</option><option value="orthographic">${t("Orthographic")}</option></select></label><label>${t("New key interpolation")} <select data-role="interp"><option value="ease">${t("Ease")}</option><option value="smooth">${t("Smooth")}</option><option value="bezier">${t("Bezier")}</option><option value="linear">${t("Linear")}</option><option value="ease_in">${t("Ease In")}</option><option value="ease_out">${t("Ease Out")}</option></select></label>
        <button data-act="reset-camera"><i class="pi pi-refresh"></i> ${t("Reset Camera")}</button>
      </div></details>
      <details class="toolbar-menu" data-menu="show"><summary><i class="pi pi-eye"></i> ${t("Show")} <i class="pi pi-chevron-down"></i></summary><div class="menu-panel">
        <label><span><i class="pi pi-th-large"></i> ${t("Guides")}</span><input data-role="guides" type="checkbox" checked></label><label><span><i class="pi pi-table"></i> ${t("Playblast Grid")}</span><input data-role="playblast-grid" type="checkbox"></label><label><span><i class="pi pi-tag"></i> ${t("Burn-in")}</span><input data-role="burn-in" type="checkbox"></label><label><span><i class="pi pi-chart-line"></i> ${t("Speed map")}</span><input data-role="speed-heatmap" type="checkbox"></label>
        <div class="menu-divider"></div><label>${t("Proxy mode")} <select data-role="mode"><option value="omni_ref">${t("Omni Ref")}</option><option value="card_grid">${t("Card + Grid")}</option><option value="graybox">${t("Graybox")}</option><option value="grid">${t("Grid")}</option><option value="point_field">${t("Point Field")}</option><option value="wireframe">${t("Wireframe")}</option></select></label><label>${t("Card fit")} <select data-role="card-fit"><option value="contain">${t("Fit")}</option><option value="cover">${t("Fill")}</option><option value="stretch">${t("Stretch")}</option></select></label>
        <div class="menu-divider"></div><div class="menu-title">${t("Previews")}</div><label>${t("Layout")} <select data-role="preview-layout"><option value="auto">${t("Auto strip")}</option><option value="1">${t("Single")}</option><option value="2">${t("Side by side")}</option><option value="4">${t("Quad")}</option></select></label><label><span><i class="pi pi-shield"></i> ${t("Safe areas")}</span><input data-role="safe-areas" type="checkbox"></label><label><span><i class="pi pi-frame"></i> ${t("Resolution gate")}</span><input data-role="resolution-gate" type="checkbox"></label><label>${t("Aspect")} <select data-role="aspect-ratio"><option value="auto">${t("Auto")}</option><option value="16:9">16:9</option><option value="4:3">4:3</option><option value="1:1">1:1</option><option value="9:16">9:16</option><option value="2.39:1">2.39:1</option></select></label>
        <label>${t("Interface")} <select data-role="ui-density"><option value="basic">${t("Basic")}</option><option value="animation">${t("Animation")}</option><option value="advanced" selected>${t("Advanced")}</option></select></label>
      </div></details>
      <details class="toolbar-menu" data-menu="output"><summary><i class="pi pi-send"></i> ${t("Output")} <i class="pi pi-chevron-down"></i></summary><div class="menu-panel right">
        <label>${t("Playblast camera")} <select data-role="playblast-camera"></select></label><label>${t("H3 preset")} <select data-role="proxy-preset"><option value="balanced">${t("Balanced")}</option><option value="parallax">${t("Parallax")}</option><option value="subject">${t("Subject")}</option><option value="debug">${t("Debug")}</option></select></label><label>${t("Encoder")} <select data-role="encoder"><option value="auto">${t("WebCodecs")}</option><option value="realtime">${t("Realtime fallback")}</option></select></label>
        <div class="menu-divider"></div><div class="setup-badge" data-role="setup-badge" hidden></div><div data-role="setup-issues"></div>
      </div></details>
      <span class="status" data-role="status">${t("Ready")}</span>
    </div>
    <div class="viewport-wrap">
      <canvas tabindex="0"></canvas>
      <div class="viewport-actions"><button class="primary" data-act="record" title="${t("Record proxy playblast")}"><i class="pi pi-video"></i> ${t("Playblast Record")}</button><button data-act="h3-setup" title="${t("Create the H3 reference nodes")}"><i class="pi pi-bolt"></i> ${t("H3 Setup")}</button></div>
      <div class="view-nav"><i class="pi pi-eye"></i><select data-role="view-mode" title="${t("Editor viewport view")}"><option value="camera">${t("Camera")}</option><option value="perspective">${t("Perspective")}</option><option value="top">${t("Top")}</option><option value="right">${t("Right")}</option><option value="left">${t("Left")}</option><option value="bottom">${t("Bottom")}</option></select><button data-act="toggle-camera-view" title="${t("Show or hide camera preview strip")}"><i class="pi pi-video"></i></button></div>
      <div class="viewport-state" data-role="viewport-state"></div>
      <div class="hud" data-role="hud"></div>
      <div class="viewport-inspector">
        <div class="menu-title">${t("Scene")}</div><div class="scene-tree" data-role="objects"></div>
        <div class="menu-title" data-role="selected-name">${t("Camera")}</div>
        <div class="entity-panel" data-role="object-panel">
          <div class="transform-tools"><button data-transform-mode="translate" title="${t("Translate (T)")}">T</button><button data-transform-mode="rotate" title="${t("Rotate (R)")}">R</button><button data-transform-mode="scale" title="${t("Scale (S)")}">S</button><select data-role="gizmo-space" title="${t("Transform space")}"><option value="world">${t("World")}</option><option value="local">${t("Local")}</option></select></div>
          <div class="animation-row"><i class="pi pi-palette"></i><select data-role="object-material" title="${t("Viewport material")}"><option value="textured">${t("Textures")}</option><option value="checker">${t("Checker")}</option><option value="neutral">${t("Neutral")}</option><option value="wireframe">${t("Wireframe")}</option></select></div>
          <div class="animation-row"><i class="pi pi-sitemap"></i><select data-role="object-parent" title="${t("Parent object (world transform follows parent)")}"><option value="">${t("No parent")}</option></select></div>
          <div class="viewport-grid"><label><span>${t("Translate X")}</span><input data-role="object-x" type="number" step="0.1"></label><label><span>${t("Translate Y")}</span><input data-role="object-y" type="number" step="0.1"></label><label><span>${t("Translate Z")}</span><input data-role="object-z" type="number" step="0.1"></label><label><span>${t("Rotate X")}</span><input data-role="object-rx" type="number" step="1"></label><label><span>${t("Rotate Y")}</span><input data-role="object-ry" type="number" step="1"></label><label><span>${t("Rotate Z")}</span><input data-role="object-rz" type="number" step="1"></label><label><span>${t("Scale X")}</span><input data-role="object-sx" type="number" min="0.01" step="0.1"></label><label><span>${t("Scale Y")}</span><input data-role="object-sy" type="number" min="0.01" step="0.1"></label><label><span>${t("Scale Z")}</span><input data-role="object-sz" type="number" min="0.01" step="0.1"></label></div>
          <div class="animation-row" data-role="animation-row" hidden><i class="pi pi-play-circle"></i><select data-role="animation-select" title="${t("Animation clip")}"></select></div>
        </div>
        <div class="entity-panel viewport-grid" data-role="camera-panel" hidden><label><span>${t("Position X")}</span><input data-role="camera-px" type="number" step="0.1"></label><label><span>${t("Position Y")}</span><input data-role="camera-py" type="number" step="0.1"></label><label><span>${t("Position Z")}</span><input data-role="camera-pz" type="number" step="0.1"></label><label><span>${t("Target X")}</span><input data-role="camera-tx" type="number" step="0.1"></label><label><span>${t("Target Y")}</span><input data-role="camera-ty" type="number" step="0.1"></label><label><span>${t("Target Z")}</span><input data-role="camera-tz" type="number" step="0.1"></label><label><span>${t("FOV")}</span><input data-role="camera-fov" type="number" min="5" max="150" step="0.1"></label><label><span>${t("Roll")}</span><input data-role="camera-roll" type="number" min="-180" max="180" step="0.1"></label><label><span>${t("Near Clip")}</span><input data-role="camera-near" type="number" min="0.0001" step="0.001"></label><label><span>${t("Far Clip")}</span><input data-role="camera-far" type="number" min="0.0002" step="1"></label></div>
        <div class="animation-row"><i class="pi pi-images"></i><select data-role="reference-select" title="${t("Upstream reference")}"><option value="0">${t("Upstream 1")}</option></select></div>
      </div>
    </div>
    <div class="camera-view-row" data-role="camera-view-row"><div class="camera-preview-strip" data-role="camera-previews"></div><button class="camera-strip-close" data-act="toggle-camera-view" title="${t("Hide camera previews")}"><i class="pi pi-times"></i></button></div>
    <div class="timeline">
      <div class="row timeline-toolbar">
        <button class="icon-button" data-act="play" title="${t("Play / Stop (Space)")}" aria-label="${t("Play timeline")}"><i class="pi pi-play"></i></button><button class="icon-button" data-act="key" title="${t("Insert / Update Key (I)")}" aria-label="${t("Insert or update key")}"><i class="pi pi-plus-circle"></i></button><button class="icon-button" data-act="auto-key" title="${t("Auto Key off")}" aria-label="${t("Toggle Auto Key")}" aria-pressed="false"><i class="pi pi-circle-fill"></i></button><button class="icon-button" data-act="delete-key" title="${t("Delete Selected Key")}" aria-label="${t("Delete selected key")}"><i class="pi pi-trash"></i></button><button class="icon-button" data-act="copy-key" title="${t("Copy Key (Ctrl/Cmd+C)")}" aria-label="${t("Copy selected key")}"><i class="pi pi-copy"></i></button><button class="icon-button" data-act="paste-key" title="${t("Paste Key (Ctrl/Cmd+V)")}" aria-label="${t("Paste key at playhead")}"><i class="pi pi-clipboard"></i></button><span class="toolbar-divider"></span>
        <button class="icon-button" data-act="previous-key" title="${t("Previous keyframe (,)")}" aria-label="${t("Previous keyframe")}"><i class="pi pi-fast-backward"></i></button><button class="icon-button" data-act="previous-frame" title="${t("Previous frame (Left Arrow)")}" aria-label="${t("Previous frame")}"><i class="pi pi-step-backward"></i></button>
        <strong>${t("Frame")}</strong><input data-role="frame" type="number" min="0" value="0"><input data-role="scrub" type="range" min="0" max="119" value="0"><span data-role="time">00:00.000</span><label>${t("Duration")} <input data-role="duration-seconds" type="number" min="0.25" max="120" step="0.25" value="5"></label><label>${t("FPS")} <input data-role="timeline-fps" type="number" min="1" max="120" step="1" value="24"></label>
        <button class="icon-button" data-act="next-frame" title="${t("Next frame (Right Arrow)")}" aria-label="${t("Next frame")}"><i class="pi pi-step-forward"></i></button><button class="icon-button" data-act="next-key" title="${t("Next keyframe (.)")}" aria-label="${t("Next keyframe")}"><i class="pi pi-fast-forward"></i></button>
        <span class="toolbar-divider"></span><button class="icon-button" data-act="loop" title="${t("Loop playback")}" aria-label="${t("Loop playback")}" aria-pressed="false"><i class="pi pi-replay"></i></button><button class="icon-button" data-act="range-start" title="${t("Set playback range start at playhead")}" aria-label="${t("Set playback range start")}">[</button><button class="icon-button" data-act="range-end" title="${t("Set playback range end at playhead")}" aria-label="${t("Set playback range end")}">]</button><button class="icon-button" data-act="range-clear" title="${t("Clear playback range")}" aria-label="${t("Clear playback range")}"><i class="pi pi-times"></i></button>
        <span class="toolbar-divider"></span><button class="icon-button" data-act="toggle-timecode" title="${t("Toggle time / timecode display")}" aria-label="${t("Toggle timecode mode")}"><i class="pi pi-clock"></i></button><button class="icon-button" data-act="toggle-snap" title="${t("Toggle keyframe snapping")}" aria-label="${t("Toggle snapping")}" aria-pressed="true"><i class="pi pi-thumbtack"></i></button><label>${t("Snap")} <input data-role="snap-frames" type="number" min="1" max="24" step="1" value="1" style="width:44px"></label>
        <span class="timeline-summary" data-role="timeline-summary">${t("1 key")}</span>
      </div>
      <div class="keys" data-role="keys" tabindex="0" aria-label="${t("Camera keyframe timeline")}"></div>
      <details class="curve-editor" open><summary title="${t("Open or close the animation curve editor")}"><i class="pi pi-chart-line"></i><strong data-role="curve-title">${t("Camera Curve Editor")}</strong><span class="hint">${t("drag points to edit values · right-click for options")}</span></summary><div class="curve-toolbar"><select data-role="curve-group" title="${t("Choose the animated channels displayed in the graph")}"><option value="position">${t("Position XYZ")}</option><option value="target">${t("Target XYZ")}</option><option value="lens">${t("FOV / Roll / Zoom")}</option></select><button class="curve-mode" data-curve-mode="linear" title="${t("Straight interpolation after the selected key")}">${t("Linear")}</button><button class="curve-mode" data-curve-mode="smooth" title="${t("Smooth interpolation after the selected key")}">${t("Smooth")}</button><button class="curve-mode" data-curve-mode="bezier" title="${t("Bézier easing after the selected key")}">${t("Bezier")}</button><button class="curve-mode" data-curve-mode="ease_in" title="${t("Ease into motion after the selected key")}">${t("Ease In")}</button><button class="curve-mode" data-curve-mode="ease_out" title="${t("Ease out of motion after the selected key")}">${t("Ease Out")}</button><button class="curve-mode" data-curve-mode="ease" title="${t("Ease in and out after the selected key")}">${t("Ease In/Out")}</button><button class="curve-mode active" data-act="curve-handles" title="${t("Show or hide Bézier tangent handles")}" aria-pressed="true"><i class="pi pi-share-alt"></i> ${t("Handles")}</button><span class="toolbar-divider"></span><span class="hint">${t("Tangents")}</span><button class="curve-mode" data-tangent-mode="auto" title="${t("Automatic smooth tangents")}">${t("Auto")}</button><button class="curve-mode" data-tangent-mode="vector" title="${t("Straight (vector) tangents")}">${t("Vector")}</button><button class="curve-mode" data-tangent-mode="free" title="${t("Independent tangent handles")}">${t("Free")}</button><button class="curve-mode" data-tangent-mode="aligned" title="${t("Mirrored tangent handles")}">${t("Aligned")}</button></div><canvas class="curve-canvas" data-role="curve-canvas" title="${t("Drag a key point vertically to edit its value. Right-click for curve actions.")}"></canvas></details>
      <details class="compact-panel key-editor" data-role="key-editor" data-empty="false" open><summary><i class="pi pi-key"></i><strong data-role="selected-key-label">${t("Key @ 0")}</strong><span class="hint">${t("yellow selected · red editing")}</span></summary><div class="panel-body">
        <div class="key-editor-header"><button class="icon-button" data-act="update-key" title="${t("Update key from current view")}" aria-label="${t("Update key from current view")}"><i class="pi pi-refresh"></i></button><button class="icon-button" data-act="view-key" title="${t("Load key view")}" aria-label="${t("Load selected key view")}"><i class="pi pi-eye"></i></button><span class="hint">${t("A selected key accepts one canvas edit. Auto Key records every camera edit at the playhead.")}</span></div>
        <div class="key-editor-grid">
          <label>${t("Frame")} <input data-role="key-frame" type="number" min="0" value="0"></label>
          <label>${t("Interpolation")} <select data-role="key-interp"><option value="ease">${t("Ease")}</option><option value="smooth">${t("Smooth")}</option><option value="bezier">${t("Bezier")}</option><option value="linear">${t("Linear")}</option><option value="ease_in">${t("Ease In")}</option><option value="ease_out">${t("Ease Out")}</option></select></label>
          <label>${t("Pos X")} <input data-role="key-px" type="number" step="0.1"></label><label>${t("Pos Y")} <input data-role="key-py" type="number" step="0.1"></label><label>${t("Pos Z")} <input data-role="key-pz" type="number" step="0.1"></label>
          <label>${t("Target X")} <input data-role="key-tx" type="number" step="0.1"></label><label>${t("Target Y")} <input data-role="key-ty" type="number" step="0.1"></label><label>${t("Target Z")} <input data-role="key-tz" type="number" step="0.1"></label>
          <label>${t("FOV")} <input data-role="key-fov" type="number" min="5" max="150" step="0.1"></label><label>${t("Roll")} <input data-role="key-roll" type="number" min="-180" max="180" step="0.1"></label><label>${t("Zoom")} <input data-role="key-zoom" type="number" min="0.01" step="0.05"></label><label>${t("Near Clip")} <input data-role="key-near" type="number" min="0.0001" step="0.001"></label><label>${t("Far Clip")} <input data-role="key-far" type="number" min="0.0002" step="1"></label>
          <label>${t("Camera")} <select data-role="key-camera-type"><option value="perspective">${t("Perspective")}</option><option value="orthographic">${t("Orthographic")}</option></select></label>
        </div></div></details>
    </div>
    <details class="help"><summary>${t("OmniCam help")}</summary><p>${t("Compose a frame, press I, scrub, move the camera and press I again. Space previews the move; Playblast records the neutral motion reference.")}</p><p>${t("The proxy communicates camera motion, not final appearance. Use H3 Setup for Omni Reference, Wan Native Camera for core Plücker conditioning, or the pinned ATI/LTX adapters for their supported workflows.")}</p></details>`;
  const contextMenu = document.createElement("div");
  contextMenu.className = "context-menu";
  contextMenu.dataset.role = "context-menu";
  contextMenu.setAttribute("role", "menu");
  contextMenu.hidden = true;
  root.appendChild(contextMenu);
  return root;
}
