// Explicit three.js surface used by the OmniCam viewport.
//
// Importing `* as THREE` straight from "three" pulls the whole library into
// the bundle because rollup cannot see which exports are live. Re-exporting
// only what the viewport touches lets it drop the rest.
//
// `npm run check:three` fails the build if a `THREE.<symbol>` used anywhere
// under web-src/ is missing from this list, so an omission is a build error
// rather than an `undefined` at runtime.
export {
  ACESFilmicToneMapping,
  AnimationMixer,
  AxesHelper,
  Box3,
  Box3Helper,
  BoxGeometry,
  BufferGeometry,
  CanvasTexture,
  CatmullRomCurve3,
  Color,
  ConeGeometry,
  CylinderGeometry,
  DataTexture,
  DirectionalLight,
  DoubleSide,
  EquirectangularReflectionMapping,
  Float32BufferAttribute,
  GridHelper,
  Group,
  HemisphereLight,
  Line,
  Line3,
  LineBasicMaterial,
  LineDashedMaterial,
  LineSegments,
  MathUtils,
  Matrix4,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  NoToneMapping,
  OrthographicCamera,
  PCFSoftShadowMap,
  PMREMGenerator,
  PerspectiveCamera,
  Plane,
  PlaneGeometry,
  Points,
  PointsMaterial,
  RGBAFormat,
  Quaternion,
  Raycaster,
  RepeatWrapping,
  RingGeometry,
  SRGBColorSpace,
  Scene,
  ShadowMaterial,
  SkeletonHelper,
  SphereGeometry,
  Texture,
  TextureLoader,
  TubeGeometry,
  Vector2,
  Vector3,
  VideoTexture,
  WebGLRenderer,
  WireframeGeometry,
} from "three";
