from __future__ import annotations

import json

from ..core.track import OmniCamTrack


def build_blender_script(track: OmniCamTrack, world_scale: float = 1.0) -> str:
    payload = json.dumps(track.to_dict())
    return f'''# Generated by ComfyUI-Majoor-OmniCam
import bpy
import json
import math
from mathutils import Quaternion, Vector

TRACK = json.loads({payload!r})
WORLD_SCALE = {float(world_scale)!r}
scene = bpy.context.scene
scene.render.resolution_x = TRACK["width"]
scene.render.resolution_y = TRACK["height"]
scene.fps = TRACK["fps"]
scene.frame_start = 0
scene.frame_end = TRACK["duration_frames"] - 1

cam_data = bpy.data.cameras.new("OmniCam")
cam_obj = bpy.data.objects.new("OmniCam", cam_data)
scene.collection.objects.link(cam_obj)
scene.camera = cam_obj
cam_obj.rotation_mode = 'QUATERNION'
cam_obj["omnicam_target_distance"] = 1.0

def scaled(values):
    return [float(value) * WORLD_SCALE for value in values]

def set_camera(camera):
    position = Vector(scaled(camera["position"]))
    target = Vector(scaled(camera["target"]))
    direction = target - position
    distance = max(direction.length, 1e-6)
    look = direction.to_track_quat('-Z', 'Y')
    roll = Quaternion(direction.normalized(), -math.radians(float(camera.get("roll", 0.0))))
    cam_obj.location = position
    cam_obj.rotation_quaternion = roll @ look
    cam_obj["omnicam_target_distance"] = distance
    cam_data.type = 'ORTHO' if camera.get("camera_type") == 'orthographic' else 'PERSP'
    cam_data.angle = math.radians(float(camera.get("fov", 35.0)))
    cam_data.ortho_scale = 10.0 / max(0.01, float(camera.get("zoom", 1.0))) * WORLD_SCALE

interpolation = {{}}
for key in TRACK["keyframes"]:
    frame = int(key["frame"])
    scene.frame_set(frame)
    set_camera(key["camera"])
    cam_obj.keyframe_insert(data_path="location", frame=frame)
    cam_obj.keyframe_insert(data_path="rotation_quaternion", frame=frame)
    cam_obj.keyframe_insert(data_path='["omnicam_target_distance"]', frame=frame)
    cam_data.keyframe_insert(data_path="angle", frame=frame)
    cam_data.keyframe_insert(data_path="ortho_scale", frame=frame)
    interpolation[frame] = key.get("interpolation", "ease")

for owner in (cam_obj, cam_data):
    action = owner.animation_data.action if owner.animation_data else None
    if not action:
        continue
    for curve in action.fcurves:
        for point in curve.keyframe_points:
            mode = interpolation.get(round(point.co.x), "ease")
            point.interpolation = 'LINEAR' if mode == "linear" else 'BEZIER'
            point.easing = {{"ease_in": 'EASE_IN', "ease_out": 'EASE_OUT'}}.get(mode, 'AUTO')

def add_proxy(obj):
    location = scaled(obj.get("position", [0, 0, 0]))
    size = obj.get("size", [1, 1, 1])
    kind = obj.get("type", "null")
    if kind in {{"cube", "card", "human"}}:
        bpy.ops.mesh.primitive_cube_add(location=location)
        proxy = bpy.context.object
        dimensions = [size[0], size[1], size[2] if len(size) > 2 else 0.02]
        proxy.scale = [max(0.001, float(value) * WORLD_SCALE * 0.5) for value in dimensions]
    elif kind == "sphere":
        bpy.ops.mesh.primitive_uv_sphere_add(location=location, radius=float(size[0]) * WORLD_SCALE * 0.5)
        proxy = bpy.context.object
    else:
        proxy = bpy.data.objects.new(obj.get("name", "OmniCam Null"), None)
        proxy.location = location
        proxy.empty_display_type = 'PLAIN_AXES'
        scene.collection.objects.link(proxy)
    proxy.name = obj.get("name", kind.title())

for obj in TRACK.get("objects", []):
    if obj.get("enabled", True):
        add_proxy(obj)

def export_omnicam(path, frames=None):
    frames = frames or sorted({{int(key["frame"]) for key in TRACK["keyframes"]}})
    keys = []
    for frame in frames:
        scene.frame_set(frame)
        position = cam_obj.location / WORLD_SCALE
        forward = cam_obj.rotation_quaternion @ Vector((0, 0, -1))
        distance = float(cam_obj.get("omnicam_target_distance", 1.0)) / WORLD_SCALE
        target = position + forward * distance
        keys.append({{
            "frame": frame,
            "camera": {{
                "position": list(position), "target": list(target),
                "fov": math.degrees(cam_data.angle), "roll": 0.0,
                "camera_type": "orthographic" if cam_data.type == 'ORTHO' else "perspective",
                "zoom": 10.0 * WORLD_SCALE / max(cam_data.ortho_scale, 1e-6), "near": cam_data.clip_start, "far": cam_data.clip_end,
            }},
            "interpolation": interpolation.get(frame, "ease"),
        }})
    result = dict(TRACK)
    result["keyframes"] = keys
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2)
    return result

scene.frame_set(0)
print("OmniCam camera imported:", len(TRACK["keyframes"]), "keyframes")
print("Call export_omnicam(path) to export the edited Blender camera back to canonical JSON")
'''
