from __future__ import annotations

import json

from ..core.track import OmniCamTrack

SUPPORTED_UNREAL = "5.3-5.6"


def build_unreal_python_script(track: OmniCamTrack) -> str:
    payload = json.dumps(track.to_dict())
    return f'''# Generated by ComfyUI-Majoor-OmniCam for Unreal Engine {SUPPORTED_UNREAL}
import json
import math
import unreal

TRACK = json.loads({payload!r})
ASSET_PATH = "/Game/OmniCam"
SEQUENCE_NAME = "OmniCamSequence"

def ue_position(value):
    return unreal.Vector(float(value[2]) * 100.0, float(value[0]) * 100.0, float(value[1]) * 100.0)

def omnicam_position(value):
    return [float(value.y) / 100.0, float(value.z) / 100.0, float(value.x) / 100.0]

def look_rotation(position, target, roll):
    direction = ue_position(target) - ue_position(position)
    horizontal = math.hypot(direction.x, direction.y)
    return unreal.Rotator(math.degrees(math.atan2(direction.z, horizontal)), math.degrees(math.atan2(direction.y, direction.x)), -float(roll))

def interpolation(name):
    return unreal.MovieSceneKeyInterpolation.LINEAR if name == "linear" else unreal.MovieSceneKeyInterpolation.AUTO

asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
sequence = unreal.load_asset(ASSET_PATH + "/" + SEQUENCE_NAME)
if sequence is None:
    sequence = asset_tools.create_asset(SEQUENCE_NAME, ASSET_PATH, unreal.LevelSequence, unreal.LevelSequenceFactoryNew())
sequence.set_display_rate(unreal.FrameRate(TRACK["fps"], 1))
sequence.set_playback_start(0)
sequence.set_playback_end(TRACK["duration_frames"])

world = unreal.EditorLevelLibrary.get_editor_world()
cam = unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.CineCameraActor, unreal.Vector())
cam.set_actor_label("OmniCam")
cam.tags = [unreal.Name("MajoorOmniCam"), unreal.Name("Schema_1")]
camera_binding = sequence.add_possessable(cam)
transform_track = camera_binding.add_track(unreal.MovieScene3DTransformTrack)
transform_section = transform_track.add_section()
transform_section.set_range(0, TRACK["duration_frames"])
transform_channels = transform_section.get_channels()

component = cam.get_cine_camera_component()
component_binding = sequence.add_possessable(component)
component_binding.set_parent(camera_binding)
lens_track = component_binding.add_track(unreal.MovieSceneFloatTrack)
lens_track.set_property_name_and_path("CurrentFocalLength", "CurrentFocalLength")
lens_section = lens_track.add_section()
lens_section.set_range(0, TRACK["duration_frames"])
lens_channel = lens_section.get_channels()[0]

for key in TRACK["keyframes"]:
    frame = unreal.FrameNumber(int(key["frame"]))
    camera = key["camera"]
    location = ue_position(camera["position"])
    rotation = look_rotation(camera["position"], camera["target"], camera.get("roll", 0.0))
    values = [location.x, location.y, location.z, rotation.roll, rotation.pitch, rotation.yaw, 1.0, 1.0, 1.0]
    mode = interpolation(key.get("interpolation", "ease"))
    for channel, value in zip(transform_channels, values):
        channel.add_key(frame, value, interpolation=mode)
    sensor_height = float(component.get_editor_property("filmback").sensor_height)
    focal_length = sensor_height / (2.0 * math.tan(math.radians(float(camera.get("fov", 35.0))) * 0.5))
    lens_channel.add_key(frame, focal_length, interpolation=mode)

first = TRACK["keyframes"][0]["camera"]
cam.set_actor_location_and_rotation(ue_position(first["position"]), look_rotation(first["position"], first["target"], first.get("roll", 0.0)), False, False)
unreal.LevelSequenceEditorBlueprintLibrary.open_level_sequence(sequence)
unreal.EditorAssetLibrary.save_loaded_asset(sequence)

def export_sequence(path):
    result = dict(TRACK)
    keys = []
    sensor_height = float(component.get_editor_property("filmback").sensor_height)
    for source_key in TRACK["keyframes"]:
        frame = int(source_key["frame"])
        unreal.LevelSequenceEditorBlueprintLibrary.set_current_time(frame)
        location = cam.get_actor_location()
        rotation = cam.get_actor_rotation()
        forward = cam.get_actor_forward_vector()
        position = omnicam_position(location)
        target = omnicam_position(location + forward * 100.0)
        focal_length = float(component.current_focal_length)
        fov = math.degrees(2.0 * math.atan(sensor_height / (2.0 * max(focal_length, 1e-6))))
        keys.append({{"frame": frame, "camera": {{"position": position, "target": target, "fov": fov, "roll": -rotation.roll, "camera_type": "perspective", "zoom": 1.0, "near": 0.01, "far": 10000.0}}, "interpolation": source_key.get("interpolation", "ease")}})
    result["keyframes"] = keys
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2)
    return result

print("OmniCam Level Sequence created:", sequence.get_path_name())
print("Call export_sequence(path) to export the evaluated Sequencer camera to canonical JSON")
'''
